export const APP_LIST = [
  {
    id: "science-reading-lab",
    paid: false,
    name: "Science Reading in English",
    nameJa: "レベル別 英検トレーニング 英語DE科学",
    description: "短い英文を読んで、科学の内容を理解する英語×理科クイズ教材。読む力と科学的思考を同時に伸ばします。",
    target: "中3～高2 ／ 英検準2/2級/準1対応",
    tags: ["英検", "英語", "理科", "リーディング"],
    url: "https://sunedtech-56u.pages.dev/",
    color: "#3B82F6",
    bgColor: "#EFF6FF",
    icon: "🔬",
  },
{
  id: "eiken-vocab-quiz",
  paid: false,
  name: "Eiken Vocabulary Quiz",
  nameJa: "英検単語マスター！準2級・2級・準1級",
  description: "英検準2級・2級・準1級レベルの1667語を4択クイズで出題。SRS（間違い優先出題）・コンボ・ライフ制で楽しく単語力を鍛えられます。",
  target: "中3～高3 ／ 英検準2級～準1級",
  tags: ["英検", "英語", "英単語", "英検", "語彙"],
  url: "https://sunedtech.pages.dev/",
  color: "#EC4899",
  bgColor: "#FDF2F8",
  icon: "📗",
},
  {
    id: "english-vocab-quiz",
    paid: false,
    name: "English Vocabulary Quiz",
    nameJa: "中学英単語完全マスター！",
    description: "小学校〜中3レベルの約1,550語をレベル別・ランダムに4択で出題。苦手単語の復習機能つき。",
    target: "小学校～中3 ／ 英検5級～3級前後",
    tags: ["英語", "英単語", "語彙"],
    url: "https://sun-ed-tech-u14y.vercel.app/",
    color: "#F59E0B",
    bgColor: "#FFFBEB",
    icon: "📚",
  },
   {
    id: "math-practice",
    paid: false,
    name: "Math Word Problem Practice",
    nameJa: "算数文章題 練習",
    description: "速さ・分数・割合・体積など5種類のジャンルからランダムに出題します。解説つき。",
    target: "小5 / 文章題の総合練習",
    tags: ["算数", "文章題"],
    url: "https://s5bunshodai.pages.dev/",
    color: "#0EA5E9",
    bgColor: "#E0F2FE",
    icon: "🧮",
  },
  {
    id: "kagakushiki-renshuu",
    paid: false,
    name: "Chemical Formula Practice",
    nameJa: "化学式練習",
    description: "42種類の化学式をランダム出題。単体・化合物・酸化物などカテゴリ絞り込みや間違えた問題だけやり直す機能つき。",
    target: "中1～中2 ／ 化学式の暗記・定着",
    tags: ["理科", "化学", "化学式"],
    url: "https://sun-ed-tech-kagakushiki.pages.dev/",
    color: "#10B981",
    bgColor: "#ECFDF5",
    icon: "⚗️",
  },
  {
    id: "kagaku-hannoushiki",
    paid: false,
    name: "Chemical Equation Master",
    nameJa: "化学反応式マスター",
    description: "クイズバトル・タイムアタック・係数合わせ・分子ビジュアルの4モードで化学反応式を楽しく学べるゲーム型アプリ。",
    target: "中2～中3 ／ 化学反応式の理解・定着",
    tags: ["理科", "化学", "化学反応式"],
    url: "https://sun-ed-tech-nquc.vercel.app/",
    color: "#1D9E75",
    bgColor: "#ECFDF5",
    icon: "⚗️",
  },
 {
    id: "romaji-renshuu",
    paid: false,
    name: "Romaji Practice",
    nameJa: "ローマ字れんしゅう",
    description: "キーボードでローマ字を入力する練習アプリ。小学生〜中学生のローマ字・タイピング入門に最適です。",
    target: "小3～小6 ／ ローマ字・タイピング入門",
    tags: ["ローマ字", "タイピング", "小学生"],
    url: "https://sun-ed-tech-fu65.vercel.app/",
    color: "#F97316",
    bgColor: "#FFF7ED",
    icon: "⌨️",
  },
  {
    id: "yakubun-renshuu",
    paid: false,
    name: "Fraction Simplification Practice",
    nameJa: "分数の約分れんしゅう",
    description: "かんたん・ふつう・むずかしいの3段階で約分を練習できるアプリ。ヒント機能つきで、つまずいても安心です。",
    target: "小4～中1 ／ 分数・約分の導入～定着",
    tags: ["算数", "分数", "約分"],
    url: "https://sun-ed-tech-yakubun.vercel.app/",
    color: "#8B5CF6",
    bgColor: "#F5F3FF",
    icon: "➗",
  },

];