// 問題ストック型のローカルデータです。
// 新しい問題を増やすときは、この配列に同じ形式のオブジェクトを追加してください。
// category は speed / volume / fraction / ratio / unit のいずれかにします。

export const PROBLEM_BANK = [
  // ─── 速さ・時間・距離 ──────────────────────────────────────────────
  {
    id: 'speed-001',
    category: 'speed',
    cat: '速さ・時間',
    text: '家から図書館までの道のりは 3 km です。ゆうとは自転車で時速 12 km の速さで進みました。\n図書館に着くまでに何分かかりますか。',
    parts: [{ question: 'かかった時間', answer: '15', unit: '分' }],
    explanation: '時間は「道のり ÷ 速さ」で求めます。3 ÷ 12 = 0.25 時間で、0.25 時間は 15 分です。',
  },
  {
    id: 'speed-002',
    category: 'speed',
    cat: '速さ・時間',
    text: '電車が時速 60 km で走っています。この電車が 45 分走ると、何 km 進みますか。',
    parts: [{ question: '進む道のり', answer: '45', unit: 'km' }],
    explanation: '45 分は 0.75 時間です。道のりは 60 × 0.75 = 45 km です。',
  },
  {
    id: 'speed-003',
    category: 'speed',
    cat: '速さ・時間',
    text: 'はるかさんは 1.8 km の道を 24 分で歩きました。分速何 m で歩いたことになりますか。',
    parts: [{ question: '歩く速さ', answer: '75', unit: 'm/分' }],
    explanation: '1.8 km は 1800 m です。1800 ÷ 24 = 75 なので、分速 75 m です。',
  },
  {
    id: 'speed-004',
    category: 'speed',
    cat: '速さ・時間',
    text: 'バスは分速 500 m で走っています。6 km 進むには何分かかりますか。',
    parts: [{ question: 'かかる時間', answer: '12', unit: '分' }],
    explanation: '6 km は 6000 m です。時間は 6000 ÷ 500 = 12 分です。',
  },
  {
    id: 'speed-005',
    category: 'speed',
    cat: '速さ・時間',
    text: '兄は分速 80 m、弟は分速 60 m で同じ方向に歩きます。弟が先に出発して、兄は 10 分後に出発しました。\n兄が出発したとき、弟は何 m 先にいますか。\n兄は弟に何分後に追いつきますか。',
    parts: [
      { question: '弟が先にいる道のり', answer: '600', unit: 'm' },
      { question: '追いつくまでの時間', answer: '30', unit: '分' },
    ],
    explanation: '弟は 60 × 10 = 600 m 先にいます。1 分で縮まる差は 80 - 60 = 20 m なので、600 ÷ 20 = 30 分後に追いつきます。',
  },
  {
    id: 'speed-006',
    category: 'speed',
    cat: '速さ・時間',
    text: 'まいさんは家から駅まで 1.2 km を 15 分で歩きました。駅から学校まで 800 m を 10 分で歩きました。\n全部で何 m 歩きましたか。\n全体の平均の速さは分速何 m ですか。',
    parts: [
      { question: '全部の道のり', answer: '2000', unit: 'm' },
      { question: '平均の速さ', answer: '80', unit: 'm/分' },
    ],
    explanation: '1.2 km は 1200 m なので、全部で 1200 + 800 = 2000 m です。時間は 15 + 10 = 25 分だから、平均の速さは 2000 ÷ 25 = 80 m/分です。',
  },
  {
    id: 'speed-007',
    category: 'speed',
    cat: '速さ・時間',
    text: '時速 48 km の車があります。この車の速さは分速何 m ですか。',
    parts: [{ question: '分速', answer: '800', unit: 'm/分' }],
    explanation: '48 km は 48000 m、1 時間は 60 分です。48000 ÷ 60 = 800 なので、分速 800 m です。',
  },
  {
    id: 'speed-008',
    category: 'speed',
    cat: '速さ・時間',
    text: '学校から公園まで 900 m あります。あきらさんは分速 75 m で歩きます。午後 3 時 10 分に学校を出ると、何時何分に公園に着きますか。',
    parts: [{ question: '到着時刻の分', answer: '22', unit: '分' }],
    explanation: '900 ÷ 75 = 12 なので、12 分かかります。午後 3 時 10 分の 12 分後は午後 3 時 22 分です。答え欄には分だけ入力します。',
  },
  {
    id: 'speed-009',
    category: 'speed',
    cat: '速さ・時間',
    text: 'ランナーが 400 m のトラックを 5 周しました。かかった時間は 10 分です。平均の速さは分速何 m ですか。',
    parts: [{ question: '平均の速さ', answer: '200', unit: 'm/分' }],
    explanation: '走った道のりは 400 × 5 = 2000 m です。2000 ÷ 10 = 200 なので、分速 200 m です。',
  },
  {
    id: 'speed-010',
    category: 'speed',
    cat: '速さ・時間',
    text: '船が川を下るときの速さは時速 18 km、川を上るときの速さは時速 12 km です。同じ 6 km を進むとき、下りと上りでは何分ちがいますか。',
    parts: [{ question: '時間の差', answer: '10', unit: '分' }],
    explanation: '下りは 6 ÷ 18 = 1/3 時間で 20 分、上りは 6 ÷ 12 = 1/2 時間で 30 分です。差は 10 分です。',
  },

  // ─── 体積・面積 ───────────────────────────────────────────────────
  {
    id: 'volume-001',
    category: 'volume',
    cat: '体積・面積',
    text: 'たて 8 cm、横 12 cm の長方形があります。この長方形の面積は何 cm² ですか。',
    parts: [{ question: '面積', answer: '96', unit: 'cm²' }],
    explanation: '長方形の面積は「たて × 横」です。8 × 12 = 96 cm² です。',
  },
  {
    id: 'volume-002',
    category: 'volume',
    cat: '体積・面積',
    text: '底辺 10 cm、高さ 7 cm の三角形があります。この三角形の面積は何 cm² ですか。',
    parts: [{ question: '面積', answer: '35', unit: 'cm²' }],
    explanation: '三角形の面積は「底辺 × 高さ ÷ 2」です。10 × 7 ÷ 2 = 35 cm² です。',
  },
  {
    id: 'volume-003',
    category: 'volume',
    cat: '体積・面積',
    text: 'たて 6 cm、横 9 cm、高さ 4 cm の直方体があります。この直方体の体積は何 cm³ ですか。',
    parts: [{ question: '体積', answer: '216', unit: 'cm³' }],
    explanation: '直方体の体積は「たて × 横 × 高さ」です。6 × 9 × 4 = 216 cm³ です。',
  },
  {
    id: 'volume-004',
    category: 'volume',
    cat: '体積・面積',
    text: '1 辺が 5 cm の立方体があります。この立方体の体積は何 cm³ ですか。',
    parts: [{ question: '体積', answer: '125', unit: 'cm³' }],
    explanation: '立方体の体積は「1 辺 × 1 辺 × 1 辺」です。5 × 5 × 5 = 125 cm³ です。',
  },
  {
    id: 'volume-005',
    category: 'volume',
    cat: '体積・面積',
    text: '底面積が 48 cm²、高さが 9 cm の角柱があります。この角柱の体積は何 cm³ ですか。',
    parts: [{ question: '体積', answer: '432', unit: 'cm³' }],
    explanation: '角柱の体積は「底面積 × 高さ」です。48 × 9 = 432 cm³ です。',
  },
  {
    id: 'volume-006',
    category: 'volume',
    cat: '体積・面積',
    text: 'たて 15 cm、横 20 cm の長方形の紙から、たて 5 cm、横 6 cm の長方形を切り取ります。残りの面積は何 cm² ですか。',
    parts: [{ question: '残りの面積', answer: '270', unit: 'cm²' }],
    explanation: 'もとの面積は 15 × 20 = 300 cm²、切り取る面積は 5 × 6 = 30 cm² です。残りは 300 - 30 = 270 cm² です。',
  },
  {
    id: 'volume-007',
    category: 'volume',
    cat: '体積・面積',
    text: '水そうの内側の大きさは、たて 30 cm、横 20 cm、高さ 25 cm です。この水そうをいっぱいにすると、水は何 L 入りますか。',
    parts: [{ question: '水の量', answer: '15', unit: 'L' }],
    explanation: '体積は 30 × 20 × 25 = 15000 cm³ です。1000 cm³ = 1 L なので、15000 cm³ は 15 L です。',
  },
  {
    id: 'volume-008',
    category: 'volume',
    cat: '体積・面積',
    text: '平行四辺形の底辺は 14 cm、高さは 6 cm です。この平行四辺形の面積は何 cm² ですか。',
    parts: [{ question: '面積', answer: '84', unit: 'cm²' }],
    explanation: '平行四辺形の面積は「底辺 × 高さ」です。14 × 6 = 84 cm² です。',
  },
  {
    id: 'volume-009',
    category: 'volume',
    cat: '体積・面積',
    text: '台形の上底は 6 cm、下底は 14 cm、高さは 5 cm です。この台形の面積は何 cm² ですか。',
    parts: [{ question: '面積', answer: '50', unit: 'cm²' }],
    explanation: '台形の面積は「(上底 + 下底) × 高さ ÷ 2」です。(6 + 14) × 5 ÷ 2 = 50 cm² です。',
  },
  {
    id: 'volume-010',
    category: 'volume',
    cat: '体積・面積',
    text: '長方形の面積は 72 cm²、たての長さは 8 cm です。横の長さは何 cm ですか。',
    parts: [{ question: '横の長さ', answer: '9', unit: 'cm' }],
    explanation: '横の長さは「面積 ÷ たて」です。72 ÷ 8 = 9 cm です。',
  },

  // ─── 分数計算 ─────────────────────────────────────────────────────
  {
    id: 'fraction-001',
    category: 'fraction',
    cat: '分数計算',
    text: 'ケーキの 1/3 を午前中に食べ、午後に 1/4 を食べました。合わせてケーキ全体のどれだけを食べましたか。',
    parts: [{ question: '食べた割合', answer: '7/12', unit: '' }],
    explanation: '1/3 と 1/4 を通分すると、4/12 と 3/12 です。合わせて 7/12 です。',
  },
  {
    id: 'fraction-002',
    category: 'fraction',
    cat: '分数計算',
    text: 'ジュースが 3/4 L あります。そのうち 1/2 L を飲みました。残りは何 L ですか。',
    parts: [{ question: '残り', answer: '1/4', unit: 'L' }],
    explanation: '3/4 - 1/2 を計算します。1/2 = 2/4 なので、3/4 - 2/4 = 1/4 L です。',
  },
  {
    id: 'fraction-003',
    category: 'fraction',
    cat: '分数計算',
    text: '1 本 2/5 m のリボンを 6 本つなげます。全部で何 m になりますか。',
    parts: [{ question: '全部の長さ', answer: '12/5', unit: 'm' }],
    explanation: '2/5 を 6 個分なので、2/5 × 6 = 12/5 m です。2.4 m と答えても正解です。',
  },
  {
    id: 'fraction-004',
    category: 'fraction',
    cat: '分数計算',
    text: '3/5 kg の小麦粉を、同じ量ずつ 3 つの袋に分けます。1 袋あたり何 kg ですか。',
    parts: [{ question: '1袋あたり', answer: '1/5', unit: 'kg' }],
    explanation: '3/5 ÷ 3 = 3/5 × 1/3 = 1/5 です。1 袋あたり 1/5 kg です。',
  },
  {
    id: 'fraction-005',
    category: 'fraction',
    cat: '分数計算',
    text: '水そうの 2/3 まで水が入っています。さらに全体の 1/6 の量の水を入れると、全体のどれだけになりますか。',
    parts: [{ question: '水の割合', answer: '5/6', unit: '' }],
    explanation: '2/3 = 4/6 です。4/6 + 1/6 = 5/6 になります。',
  },
  {
    id: 'fraction-006',
    category: 'fraction',
    cat: '分数計算',
    text: '畑の 5/8 に野菜を植えました。そのうち 2/8 はトマトです。トマト以外の野菜を植えた部分は、畑全体のどれだけですか。',
    parts: [{ question: 'トマト以外の部分', answer: '3/8', unit: '' }],
    explanation: '野菜を植えた 5/8 から、トマトの 2/8 を引きます。5/8 - 2/8 = 3/8 です。',
  },
  {
    id: 'fraction-007',
    category: 'fraction',
    cat: '分数計算',
    text: '1 日に 3/10 ページ分の読書ノートを書きます。5 日では何ページ分になりますか。',
    parts: [{ question: 'ページ数', answer: '3/2', unit: 'ページ' }],
    explanation: '3/10 × 5 = 15/10 = 3/2 です。1.5 ページと答えても正解です。',
  },
  {
    id: 'fraction-008',
    category: 'fraction',
    cat: '分数計算',
    text: '3/4 m のひもから 1/8 m を切り取ります。残りは何 m ですか。',
    parts: [{ question: '残りの長さ', answer: '5/8', unit: 'm' }],
    explanation: '3/4 = 6/8 です。6/8 - 1/8 = 5/8 m です。',
  },
  {
    id: 'fraction-009',
    category: 'fraction',
    cat: '分数計算',
    text: '1/6 L の薬品を 4 本分使いました。全部で何 L 使いましたか。',
    parts: [{ question: '使った量', answer: '2/3', unit: 'L' }],
    explanation: '1/6 × 4 = 4/6 = 2/3 です。全部で 2/3 L 使いました。',
  },
  {
    id: 'fraction-010',
    category: 'fraction',
    cat: '分数計算',
    text: '全体の 7/10 の作業が終わっています。残りは全体のどれだけですか。',
    parts: [{ question: '残り', answer: '3/10', unit: '' }],
    explanation: '全体は 1 = 10/10 です。10/10 - 7/10 = 3/10 です。',
  },

  // ─── 割合・百分率 ─────────────────────────────────────────────────
  {
    id: 'ratio-001',
    category: 'ratio',
    cat: '割合・百分率',
    text: '定価 2000 円の本を 20% 引きで買いました。代金はいくらですか。',
    parts: [{ question: '代金', answer: '1600', unit: '円' }],
    explanation: '20% 引きなので、支払うのは定価の 80% です。2000 × 0.8 = 1600 円です。',
  },
  {
    id: 'ratio-002',
    category: 'ratio',
    cat: '割合・百分率',
    text: 'クラス 40 人のうち、15% が欠席しました。欠席した人は何人ですか。',
    parts: [{ question: '欠席者数', answer: '6', unit: '人' }],
    explanation: '15% は 0.15 です。40 × 0.15 = 6 人です。',
  },
  {
    id: 'ratio-003',
    category: 'ratio',
    cat: '割合・百分率',
    text: 'ある店で 1200 円の商品に 10% の消費税がかかります。税込みの値段はいくらですか。',
    parts: [{ question: '税込み価格', answer: '1320', unit: '円' }],
    explanation: '税込み価格はもとの値段の 110% です。1200 × 1.1 = 1320 円です。',
  },
  {
    id: 'ratio-004',
    category: 'ratio',
    cat: '割合・百分率',
    text: 'テストは 80 点満点で、りなさんは 68 点でした。得点率は何%ですか。',
    parts: [{ question: '得点率', answer: '85', unit: '%' }],
    explanation: '得点率は 68 ÷ 80 × 100 で求めます。68 ÷ 80 = 0.85 なので 85% です。',
  },
  {
    id: 'ratio-005',
    category: 'ratio',
    cat: '割合・百分率',
    text: '500 mL のジュースのうち 30% を飲みました。飲んだ量は何 mL ですか。',
    parts: [{ question: '飲んだ量', answer: '150', unit: 'mL' }],
    explanation: '30% は 0.3 です。500 × 0.3 = 150 mL です。',
  },
  {
    id: 'ratio-006',
    category: 'ratio',
    cat: '割合・百分率',
    text: 'ある学校の児童は 600 人です。そのうち 35% が電車で通学しています。電車で通学している児童は何人ですか。',
    parts: [{ question: '人数', answer: '210', unit: '人' }],
    explanation: '35% は 0.35 です。600 × 0.35 = 210 人です。',
  },
  {
    id: 'ratio-007',
    category: 'ratio',
    cat: '割合・百分率',
    text: 'りんごを 25 個買いました。そのうち 4 個が傷んでいました。傷んでいたりんごは全体の何%ですか。',
    parts: [{ question: '割合', answer: '16', unit: '%' }],
    explanation: '4 ÷ 25 = 0.16 です。百分率にすると 16% です。',
  },
  {
    id: 'ratio-008',
    category: 'ratio',
    cat: '割合・百分率',
    text: '原価 800 円の商品に、原価の 25% の利益をつけて売ります。売値はいくらですか。',
    parts: [{ question: '売値', answer: '1000', unit: '円' }],
    explanation: '利益は 800 × 0.25 = 200 円です。売値は 800 + 200 = 1000 円です。',
  },
  {
    id: 'ratio-009',
    category: 'ratio',
    cat: '割合・百分率',
    text: '定価 3600 円のくつを 25% 引きで買いました。値引き額はいくらですか。\nまた、代金はいくらですか。',
    parts: [
      { question: '値引き額', answer: '900', unit: '円' },
      { question: '代金', answer: '2700', unit: '円' },
    ],
    explanation: '値引き額は 3600 × 0.25 = 900 円です。代金は 3600 - 900 = 2700 円です。',
  },
  {
    id: 'ratio-010',
    category: 'ratio',
    cat: '割合・百分率',
    text: 'ある本を 45 ページ読みました。これは全体の 30% です。この本は全部で何ページありますか。',
    parts: [{ question: '全部のページ数', answer: '150', unit: 'ページ' }],
    explanation: '45 ページが全体の 30% なので、全体は 45 ÷ 0.3 = 150 ページです。',
  },

  // ─── 単位換算 ─────────────────────────────────────────────────────
  {
    id: 'unit-001',
    category: 'unit',
    cat: '単位換算',
    text: '2.5 km は何 m ですか。',
    parts: [{ question: '長さ', answer: '2500', unit: 'm' }],
    explanation: '1 km = 1000 m です。2.5 × 1000 = 2500 m です。',
  },
  {
    id: 'unit-002',
    category: 'unit',
    cat: '単位換算',
    text: '3500 mL は何 L ですか。',
    parts: [{ question: 'かさ', answer: '3.5', unit: 'L' }],
    explanation: '1000 mL = 1 L です。3500 ÷ 1000 = 3.5 L です。',
  },
  {
    id: 'unit-003',
    category: 'unit',
    cat: '単位換算',
    text: '4.2 kg は何 g ですか。',
    parts: [{ question: '重さ', answer: '4200', unit: 'g' }],
    explanation: '1 kg = 1000 g です。4.2 × 1000 = 4200 g です。',
  },
  {
    id: 'unit-004',
    category: 'unit',
    cat: '単位換算',
    text: '7500 cm² は何 m² ですか。',
    parts: [{ question: '面積', answer: '0.75', unit: 'm²' }],
    explanation: '1 m² = 10000 cm² です。7500 ÷ 10000 = 0.75 m² です。',
  },
  {
    id: 'unit-005',
    category: 'unit',
    cat: '単位換算',
    text: '1 時間 20 分は何分ですか。',
    parts: [{ question: '時間', answer: '80', unit: '分' }],
    explanation: '1 時間は 60 分です。60 + 20 = 80 分です。',
  },
  {
    id: 'unit-006',
    category: 'unit',
    cat: '単位換算',
    text: '540 秒は何分ですか。',
    parts: [{ question: '時間', answer: '9', unit: '分' }],
    explanation: '1 分は 60 秒です。540 ÷ 60 = 9 分です。',
  },
  {
    id: 'unit-007',
    category: 'unit',
    cat: '単位換算',
    text: '0.8 L は何 mL ですか。',
    parts: [{ question: 'かさ', answer: '800', unit: 'mL' }],
    explanation: '1 L = 1000 mL です。0.8 × 1000 = 800 mL です。',
  },
  {
    id: 'unit-008',
    category: 'unit',
    cat: '単位換算',
    text: '12000 cm³ は何 L ですか。',
    parts: [{ question: 'かさ', answer: '12', unit: 'L' }],
    explanation: '1000 cm³ = 1 L です。12000 ÷ 1000 = 12 L です。',
  },
  {
    id: 'unit-009',
    category: 'unit',
    cat: '単位換算',
    text: '3 m 45 cm は何 cm ですか。',
    parts: [{ question: '長さ', answer: '345', unit: 'cm' }],
    explanation: '3 m は 300 cm です。300 + 45 = 345 cm です。',
  },
  {
    id: 'unit-010',
    category: 'unit',
    cat: '単位換算',
    text: '2.4 ha は何 m² ですか。',
    parts: [{ question: '面積', answer: '24000', unit: 'm²' }],
    explanation: '1 ha = 10000 m² です。2.4 × 10000 = 24000 m² です。',
  },
];
